### ISSUE TITLE
NodeJS code giving below error.

### ISSUE THREAD

**Issue by arun-msft-zz** [microsoftgraph/csharp-teams-sample-graph#12]
Hi,
When we tried NODE JS application is run via http://localhost:55065/login it shows Sign In button. On clicking this button below URL timeout:
https://localhost:55065/api/authurl 

And application get redirected to http://localhost:55065/undefined&state=%2F with below text displayed in browser

{"code":"ResourceNotFound","message":"/undefined&state=%2F does not exist"}

Please let me know what could be the error here?

Thanks & Regards,
Arun

**Comment by ElYusubov** [comment]
@arun-msft - It looks like a common resource access problem. Most probably user does not have any Teams channel or you have used a non work account.  I have used: https://developer.microsoft.com/en-us/graph/graph-explorer to login with user credentials that have access to the teams channel. Once you set-up user permissions it should work like a charm.

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
