### ISSUE TITLE
Add Member throw error - chsarp

### ISSUE THREAD

**Issue by ElYusubov** [microsoftgraph/csharp-teams-sample-graph#16]
Hi,

I am getting the the following error when "Add Member" is invoked. Basically call to ~/Home/GetMemberLoad.  What am i missing here?

![image](https://user-images.githubusercontent.com/29330538/48326154-e3732800-e605-11e8-9914-961a43a61815.png)

**Comment by nkramer** [comment]
Fixed, thanks.

**Comment by ElYusubov** [comment]
Thanks, i have verified that it works now.

**Comment by ElYusubov** [comment]
@nkramer - do you know why there is an error when clicking on "Add Team to Group":
Or what permission does logged in user requires ?

![image](https://user-images.githubusercontent.com/29330538/48455207-3f65ba00-e788-11e8-9a61-abefbc5441e9.png)
