### ISSUE TITLE
Impersonation feature

### ISSUE THREAD

**Issue by ElYusubov** [microsoftgraph/csharp-teams-sample-graph#17]
My sincere apologies to post this as an issue, however it is a real scenario that i am trying to find an answer.

Is there any road-map to allow posting on a team channel - on behalf of a user? (impersonation)

Basically, through impersonation a back-end service will be able to post a message to a team channel.
This is a scenario where a ticket is created on a app, but posted on a team's channel.

**Comment by nkramer** [comment]
I'm not sure I understand the scenario you're looking for. Is this with application permissions or user delegated? Why isn't the app posting it as coming from the app?

**Comment by butchmarshall** [comment]
We're looking this feature as well.

We have an external gallery of content we'd like to surface inside of Microsoft Teams via AdaptiveCards.

Our system has a replies system as well - we'd like to keep the Teams card and our external galleries replies in sync so the same conversation happens in both places.

Right now it doesn't look like its possible to keep these in sync.  It also doesn't seem possible to turn of AdaptiveCard replies entirely to work around the problem.
