### ISSUE TITLE
regarding can't posting replies to messages, code snippet, post. mentioning team_mates

### ISSUE THREAD

**Issue by Allauvdheenbasha** [microsoftgraph/csharp-teams-sample-graph#19]
didn't find PowerShell cmdlets and RestAPI methods for posting replies to messages, code snippet, post. mentioning team_mates.

when resources for all these post scenarios will be available for developers end? 

is it in a roadmap or not ??

**Comment by nkramer** [comment]
(dup issue) We are working on an improved API for sending messages.

**Comment by nkramer** [comment]
I'm going to close this issue out since it's not a sample issue but a product issue. Product issues are best tracked on UserVoice – see https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis?query=team
