### ISSUE TITLE
about resource for posting  posting replies to messages, code snippet, post. mentioning team_mates.

### ISSUE THREAD

**Issue by Allauvdheenbasha** [microsoftgraph/csharp-teams-sample-graph#20]
didn't find PowerShell cmdlets and RestAPI methods for posting replies to messages, code snippet, post. mentioning team_mates.

when resources for all these post scenarios will be available for developers end?

is it in a roadmap or not ??

**Comment by nkramer** [comment]
We are working on an improved API for sending messages.

**Comment by Allauvdheenbasha** [comment]
ETA for this ? what date it will be released ?

**Comment by nkramer** [comment]
We are not far enough along to provide a date.
