### ISSUE TITLE
csharp- keep getting app permission error 

### ISSUE THREAD

**Issue by ragavanrajan** [microsoftgraph/csharp-teams-sample-graph#21]
Can any one please help I have followed all the instructions as per the readme file. 

When I run the application. I am keep getting the following error message 

![image](https://user-images.githubusercontent.com/6369107/50388369-27b32580-0779-11e9-9e6e-99437abe6e79.png)

I have added the following permissions for Delegation and permissions. But still getting the same error. 

Under 'Microsoft Graph Permissions', Add 'Group.ReadWrite.All' (Read and write all groups) and 'User.ReadWrite.All' (Read and write all users' full profile) as Delegated and Application Permissions.

Any idea how to solve it

**Comment by nkramer** [comment]
Have you gotten your global admin to approve your app? The README file has a little bit about this in the Prerequisites section.

**Comment by ragavanrajan** [comment]
Thank you Nick. Silly me. I got the global admin access now. Also created E3 developer account for testing.
