### ISSUE TITLE
API for Posting messages to direct chat and group chat in MS Teams.

### ISSUE THREAD

**Issue by Allauvdheenbasha** [microsoftgraph/csharp-teams-sample-graph#27]
when can we expect API's for Posting messages to direct chat and group chat?.  is it on roadmap ?? 

reply soon pls.

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
