### ISSUE TITLE
Microsoft.Graph : One or more errors occurred. (Message: This request is forbidden.  Inner error )

### ISSUE THREAD

**Issue by Rashree138** [microsoftgraph/csharp-teams-sample-graph#31]
Hi Team,

I am getting "This request is forbidden." error when I am trying to Post/Get Graph API. 
Providing sample code which i am using: 

var tenantId = "MY-TENANTID";
            var clientId = "MY_CLIENT_ID";
            var clientSecret = "MY_CLIENT_SECRET";

            //create an authProvider
            IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
            .Create(clientId)
            .WithTenantId(tenantId)
            .WithClientSecret(clientSecret)
            .Build();

            ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);

            var graphClient = new GraphServiceClient(authProvider);

 var t= graphClient.Teams["TEAM_ID"].Channels["CHANNEL_ID"]
                .Request()
                .GetAsync().Result;

Here I am pasting screen shot of : graphClient object
=====================================
![image](https://user-images.githubusercontent.com/13681207/66116295-180e1a80-e5f0-11e9-88c0-1d32863a7247.png)

Also pasting exception detail:
======================
![image](https://user-images.githubusercontent.com/13681207/66116520-7c30de80-e5f0-11e9-8e72-349168ef7aad.png)

Please let me know if Iam doing something wrong.
My simple requirement is send to message to channel.

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
