### ISSUE TITLE
Resource not found for the segment 'chatThreads'

### ISSUE THREAD

**Issue by Rashree138** [microsoftgraph/csharp-teams-sample-graph#33]
HI Team,

Today i am getting this error while i trying to access GraphAPI for posting chant in channel.

![image](https://user-images.githubusercontent.com/13681207/69952502-560aba80-151d-11ea-9f7a-442a540002af.png)

**Comment by cAstraea** [comment]
Had the same problem and found this edge but maybe it's different or used for other things? 
https://graph.microsoft.com/beta/teams/{id}/channels/{channel}/messages

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
