### ISSUE TITLE
"AADSTS50177: User account '{EmailHidden}' from identity provider 'https://sts.windows.net/3b87dee2-7301-4fb6-bfc5-ce666251f561/' does not exist in tenant.

### ISSUE THREAD

**Issue by Rashree138** [microsoftgraph/csharp-teams-sample-graph#34]
Hi Team,

I am getting below error during generating token for GraphAPI.

Please help to get resolve this.

![image](https://user-images.githubusercontent.com/13681207/69953023-68392880-151e-11ea-921f-e4ccebe6513d.png)

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
