### ISSUE TITLE
Unable to run the sample

### ISSUE THREAD

**Issue by mjanulaitis** [microsoftgraph/csharp-teams-sample-graph#35]
I followed the instructions to the letter however when I added the port change to the project the app never ran.  Once I rolled that back to the default port 55069 in my case I get the following error:

"OpenIdConnectMessage.Error was not null, indicating an error. Error: 'invalid_request'. Error_Description (may be empty): 'AADSTS50194: Application '404e0c06-3e26-4322-b541-2d719c0acf52'(NDA Signature Notifications) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant. Trace ID: 390f3e4a-9925-4d36-ab88-90839f1b2000 Correlation ID: 3fb06c46-094a-443c-b932-36e899ff1650 Timestamp: 2019-12-10 19:29:37Z'. Error_Uri (may be empty): ''."

**Comment by cshiflett** [comment]
I have the exact same issue...followed the set up instructions to the letter.  I have no idea how to resolve.

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
