### ISSUE TITLE
How to send message from Bot application to specific user in teams

### ISSUE THREAD

**Issue by Rashree138** [microsoftgraph/csharp-teams-sample-graph#36]
Hi Team,

I need to send message to particular user in Teams from Bot application instead sending message to Channel. 
Is there any API for that?

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
