### ISSUE TITLE
This is removed in MSAL.NET v4

### ISSUE THREAD

**Issue by jasmalmk** [microsoftgraph/csharp-teams-sample-graph#42]
Getting an error from MSALPerUserMemoryTokenCache/LoadUserTokenCacheFromMemory function.
 error :  This is removed in MSAL.NET v4. Read more: https://aka.ms/msal-net-4x-cache-breaking-change

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
