### ISSUE TITLE
csharp-teams-sample-graph is not nice

### ISSUE THREAD

**Issue by FlorianGrimm** [microsoftgraph/csharp-teams-sample-graph#43]
Can somebody have a look at this code?

GraphService uses ServiceHelper.SendRequest and HttpHelpers.HttpXXX why two of them?

GraphService.GetMyId HttpResponseMessage is a IDisposable

Why do you use a setting an const?
private static string GraphRootUri = ConfigurationManager.AppSettings["ida:GraphRootUri"];
public string graphBetaEndpoint = "https://graph.microsoft.com/beta";

HttpHelpers.httpClient - HttpClient is a IDisposable

Statics.Deserialize exists 2 times with different implementations

GraphService.AddTeamToGroup(string accessToken) accessToken is never used
instead the HttpPut uses the accessToken

**Comment by jasonjoh** [comment]
Closing this as we are closing this repository and will no longer maintain it. The Teams code snippets in this sample are replicated in the [ASP.NET Core Graph Snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample). We apologize for any inconvenience.
