### ISSUE TITLE
O365 Account with Admin privileges?

### ISSUE THREAD

**Issue by btastic** [microsoftgraph/csharp-teams-sample-graph#9]
Hello there,

we would love to use the teams API to create and manage channels & teams via a third party application. However, I will not get an admin account in our company for security reasons as you can imagine.

So the question is: Will the requirements for an admin account will be lifted? And if so, do you have an ETA for when?

Thank you very much!

**Comment by mlafleur** [comment]
This is an understandably confusing topic but, to be clear, you are not required to _be_ an Admin, only that you receive "consent" from an Admin in the tenant. This might help clarify what is meant by "consent": https://massivescale.com/microsoft-v2-endpoint-user-vs-admin/

**Comment by btastic** [comment]
Oh wow I feel dumb.

Thanks for clearing that up!
